CREATE TABLE photo (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(256) NOT NULL,
	path VARCHAR(256) NOT NULL,
	tags VARCHAR(1024),
	latitude VARCHAR(256),
	longitude VARCHAR(256),
	registered TIMESTAMP
)